---
title: "a3"
author: "Abigail Chen"
output: html_document
---

```{r include=FALSE, message=FALSE, warning=FALSE}
# CLEANING THE ENVIRONMENT
rm(list=ls())

# OPENING THE LIBRARIES
library(data.table)
library(esquisse)
library(ggplot2)
library(haven)
library(huxtable)
library(lspline)
library(modelsummary)
library(pscl)
library(tidyverse)
library(xml2)
library(readr)
library(dplyr)
library(tidyverse)
library(fBasics)
```

```{r include=FALSE, message=FALSE, warning=FALSE}
#LOADING THE DATA
raw_data <- read.csv("/Users/abigailchristinechen/da/assignment/a3/US_abnb.csv", stringsAsFactors = TRUE) 
```
#Introduction#
The goal for this assignment is to find out the relationship between the prices of the various Airbnb Rentals in different cities.  The dataset has cities and sub cities under the neighbourhood column.  The next part will be about cleaning the data and filling empty cells with NA's.
```{r include=FALSE, message=FALSE, warning=FALSE}
#CLEANING THE DATA
sum(is.na(raw_data))

#checking to see which are empty
summary(raw_data) 

#empty columns filled with NA's

sum(is.na(raw_data$country))   
sum(is.na(raw_data$bathrooms))
sum(is.na(raw_data$minstay))
names(raw_data)

#filtering NA containing columns
NA_data <- raw_data[,-c(5,7,13,15,20,21)]    

complete_data<-NA_data[complete.cases(NA_data), ]

#Keeping only useful variables
sig_data <- complete_data[,c(4:11)] 

 #finding outliers in price 
outliers<-boxplot(sig_data$price)$out

 #removing outliers
sig_data1<-sig_data[-which(sig_data$price %in% outliers),]

outliers2<-boxplot(sig_data1$bedrooms)$out
data<-sig_data1[-which(sig_data1$bedrooms %in% outliers2),]
clean_data.csv <- write.csv(data)
# write.csv(DayData,"DayData.csv", row.names = FALSE)
```

```{r include=FALSE, message=FALSE, warning=FALSE}
#Data Exploration & Visualization

summary(data)
head(data,2)
names(data)
str(data)

#Bar plot based on types of room
ggplot(data, aes(x=room_type, fill=room_type)) + geom_bar() +
  labs(title = "Plot of types of rooms", x="Types of Rooms",fill="Types of Rooms") +
  theme(plot.background = element_rect(fill = "ivory2")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))

#Plot of cities
ggplot(data, aes(x=city, fill=city)) + geom_bar() +
  labs(title = "Plot of cities", x="Cities",fill="Cities") +
  theme(plot.background = element_rect(fill = "ivory2")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))

#Box plot of prices based on cities
ggplot(data, aes(x=city, y=price)) + geom_boxplot(outlier.colour = "red") +
  labs(title = "Plot of Prices based on cities", x="Cities",y="Price") +
  theme(plot.background = element_rect(fill = "ivory2")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))
```

```{r include=FALSE, message=FALSE, warning=FALSE}
#Rating of customers
#Converting overall satisfaction into high(1) & Low (0) ratings
data$overall_satisfaction <- cut(data$overall_satisfaction, breaks = c(-1,3.5,5), labels=c("0","1"))

#BoxPlot of ratings based on accommodates
ggplot(data, aes(x=overall_satisfaction,y=accommodates,)) + geom_boxplot() +
  labs(title = "BoxPlot of ratings based on accommodates", x="Ratings", y="Accommodates") +
  theme(plot.background = element_rect(fill = "lightsalmon")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))

#BoxPlot of ratings based on number of bedrooms
ggplot(data, aes(x=overall_satisfaction,y=bedrooms)) + geom_boxplot() +
  labs(title = "BoxPlot of ratings based on number of bedrooms", x="Ratings", y="No. of Bedrooms") +
  theme(plot.background = element_rect(fill = "darkseagreen1")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))

#BoxPlot of ratings based on price
ggplot(data, aes(x=overall_satisfaction,y=price)) + geom_boxplot() +
  labs(title = "BoxPlot of ratings based on price", x="Ratings", y="Price") +
  theme(plot.background = element_rect(fill = "rosybrown")) +
  theme(plot.title = element_text(hjust=0.5, face = "italic", color = "darkred"))

names(data)
```


```{r include=FALSE, message=FALSE, warning=FALSE}
#Models
linear_model <- lm(price~city+overall_satisfaction, data=data)
summary(linear_model)

sample=sample.split(data, SplitRatio = 0.7)
train=subset(data, sample==TRUE)
test=subset(data, sample==FALSE)

logit_model <- glm(overall_satisfaction~price,family = binomial(link = "logit"),data=train)
summary(logit_model)
margins(logit_model)
logit_pred <- predict(logit_model,test)
logit_cm <- table(test$overall_satisfaction,logit_pred)

# accuracy of prediction of model
sum(diag(logit_cm)) /sum(logit_cm) 

probit_model <- glm(overall_satisfaction~price+city, family = binomial(link = "probit"),data=train)
summary(probit_model)
margins(probit_model)

probit_pred <- predict(probit_model,test)
probit_cm <- table(test$overall_satisfaction,probit_pred)

#accuracy of prediction of model
sum(diag(probit_cm)) / sum(probit_cm) 
```






